#
# This file is part of Access Control module for the Storm platform..
# Copyright (C) 2021 INPE.
#
# Authentication module for the Storm platform. is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: 2

sphinx:
    configuration: docs/sphinx/conf.py

formats: []

python:
    version: 3.7

    install:
        - method: pip
          path: .
          extra_requirements:
              - docs
